import { detectCapabilities, buildCapabilityPlan, resolveCapabilities, type Capability } from "./capabilityPlan.js";
import { CapabilityPlanStore } from "./capabilityPlanApproval.js";

export interface CapabilityPlanDraft {
  planId: string;
  goal: string;
  capabilities: string[];
  steps: Array<{
    id: string;
    capability: string;
    description: string;
    tool?: string;
    risk: "low" | "medium" | "high" | "critical";
    requiresApproval: boolean;
  }>;
  notes: string;
}

export function generatePlanForApproval(task: string, allowedCapabilities?: Capability[]): CapabilityPlanDraft {
  const caps = resolveCapabilities(task, allowedCapabilities ?? detectCapabilities(task));
  const plan = buildCapabilityPlan(task, caps);

  const record = CapabilityPlanStore.create({
    planId: "",
    goal: plan.goal,
    status: "draft",
    capabilities: caps,
    steps: plan.steps.map((step) => ({
      id: step.id,
      capability: step.tool?.name.replace("capability.", "") ?? "unknown",
      description: step.description,
      tool: step.tool?.name,
      risk: step.tool?.risk ?? "low",
      requiresApproval: step.requiresApproval ?? false,
    })),
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    notes: "Plan generated by the agent. Awaiting approval before execution.",
  });

  const safePlan = CapabilityPlanStore.get(record.planId);
  if (!safePlan) {
    throw new Error("Plan could not be written to the approval store.");
  }

  return {
    planId: safePlan.planId,
    goal: safePlan.goal,
    capabilities: safePlan.capabilities,
    steps: safePlan.steps,
    notes: safePlan.notes ?? "Plan generated by the agent. Awaiting approval before execution.",
  };
}

export function approvePlan(planId: string, approvedBy: string, approvals: Array<{ stepId: string; approved: boolean; reason?: string }>): boolean {
  const result = CapabilityPlanStore.approve(planId, approvedBy, approvals);
  return Boolean(result && result.status === "approved");
}

export function getPlan(planId: string) {
  return CapabilityPlanStore.get(planId);
}
