import { detectCapabilities, buildCapabilityPlan, resolveCapabilities, type Capability } from "./capabilityPlan.js";
import { CapabilityPlanStore } from "./capabilityPlanApproval.js";

export interface CapabilityPlanDraft {
  planId: string;
  ownerId: string;
  goal: string;
  capabilities: string[];
  steps: Array<{
    id: string;
    capability: string;
    description: string;
    tool?: string;
    risk: "low" | "medium" | "high" | "critical";
    requiresApproval: boolean;
  }>;
  notes: string;
}

export function generatePlanForApproval(task: string, ownerId: string, allowedCapabilities?: Capability[]): CapabilityPlanDraft {
  if (!ownerId.trim()) throw new Error("An ownerId is required.");

  const caps = resolveCapabilities(task, allowedCapabilities ?? detectCapabilities(task));
  const plan = buildCapabilityPlan(task, caps);

  const record = CapabilityPlanStore.create({
    ownerId,
    goal: plan.goal,
    status: "draft",
    capabilities: caps,
    steps: plan.steps.map((step) => ({
      id: step.id,
      capability: step.tool?.name.replace("capability.", "") ?? "unknown",
      description: step.description,
      tool: step.tool?.name,
      risk: step.tool?.risk ?? "low",
      requiresApproval: true,
    })),
    notes: "Plan generated by the agent. Awaiting explicit approval before execution.",
  });

  return {
    planId: record.planId,
    ownerId: record.ownerId,
    goal: record.goal,
    capabilities: record.capabilities,
    steps: record.steps.map(({ approved: _approved, ...step }) => step),
    notes: record.notes ?? "Plan generated by the agent. Awaiting explicit approval before execution.",
  };
}

export function approvePlan(planId: string, approvedBy: string, approvals: Array<{ stepId: string; approved: boolean; reason?: string }>): boolean {
  const result = CapabilityPlanStore.approve(planId, approvedBy, approvals);
  return Boolean(result && result.status === "approved");
}

export function getPlan(planId: string) {
  return CapabilityPlanStore.get(planId);
}
