// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/get-credits.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_credits_default = defineTool({
  name: "get_credits",
  title: "Get my credits",
  description: "Return the signed-in user's current AI Tor credit tier, credits used, and daily reset time.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("user_credits").select("paid_tier, used, reset_at, updated_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const row = data ?? { paid_tier: "registered", used: 0, reset_at: null, updated_at: null };
    return {
      content: [{ type: "text", text: JSON.stringify(row) }],
      structuredContent: { credits: row }
    };
  }
});

// src/lib/mcp/tools/list-uap-sightings.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_uap_sightings_default = defineTool2({
  name: "list_uap_sightings",
  title: "List UAP sightings",
  description: "List recent UAP (Unidentified Aerial Phenomena) sightings tracked by AI Tor. Optional filter by minimum severity and result limit.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of sightings to return (default 10)."),
    severity: z.enum(["low", "medium", "high", "critical"]).optional().describe("Filter to sightings at this severity.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, severity }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser2(ctx).from("uap_sightings").select("id, location, lat, lon, type, category, severity, description, source, source_url, date_reported").order("date_reported", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (severity) q = q.eq("severity", severity);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { sightings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-knowledge.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.108.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_knowledge_default = defineTool3({
  name: "search_knowledge",
  title: "Search AI Tor knowledge base",
  description: "Full-text substring search across AI Tor's skills knowledge base (titles and content). Returns matching documents with title, source, category and URL.",
  inputSchema: {
    query: z2.string().trim().min(2).describe("Search text. Matched against title and content."),
    limit: z2.number().int().min(1).max(20).optional().describe("Maximum results (default 5).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const pattern = `%${query.replace(/[%_]/g, (m) => `\\${m}`)}%`;
    const { data, error } = await supabaseForUser3(ctx).from("skills_documents").select("id, title, source, category, url, content").or(`title.ilike.${pattern},content.ilike.${pattern}`).limit(limit ?? 5);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const results = (data ?? []).map((d) => ({
      ...d,
      content: d.content?.slice(0, 400) ?? ""
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(results) }],
      structuredContent: { results }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wkdtvrxavkhbifjtvvdw";
var mcp_default = defineMcp({
  name: "aitor-mcp",
  title: "AI Tor",
  version: "0.1.0",
  instructions: "Tools exposed by AI Tor \u2014 the AlienFlow DAO tactical intelligence assistant. Use `get_credits` to see the signed-in user's remaining AI Tor credits, `list_uap_sightings` for recent UAP intel, and `search_knowledge` to search the AI Tor knowledge base.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_credits_default, list_uap_sightings_default, search_knowledge_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
